### ISSUE TITLE
Netcam streams are barely picked up (actual master branch)

### ISSUE THREAD

**Issue by axeljerabek** [Motion-Project/motionplus#194] opened 2024-11-12 13:53 UTC
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.5.x

### What was the install method?

Built from source code

### What is base architecture?

x86/x64

### What is the distro being used?

Ubuntu

### Disto version number

24.04

### Camera/Sound type(s) being used?

Network camera with RTSP

### Describe the issue/problem and steps to reproduce

The release version 0.2.2 works quite ok with netcam streams. Sometimes they are not picked up and motionplus has to be restarted. I would prefer the actual master branch, since the CPU load is a lot less and the videos seem to be better (less stuttering). But motionplus has to be restarted over and over again to pick up all 4 netcam streams over rtmp/nginx streaming als flv. Could you have a look at it if you got time? Otherwise, I appreciate your effort with this software. Thanks for your hard work!

### Relevant MotionPlus log output (at log_level 8)

```shell
Nov 12 14:32:07 [NTC][NET][cl105:ZeroCam] noimage: Checking for camera every 30 seconds.
Nov 12 14:32:07 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:32:38 [NTC][VID][cl105:ZeroCam] netcam_start: Norm: Opening Netcam
Nov 12 14:32:47 [NTC][NET][cl105:ZeroCam] open_context: Norm:Unable to open camera(ZeroCam):Input/output error
Nov 12 14:32:47 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:32:47 [NTC][NET][cl105:ZeroCam] noimage: Camera did not reconnect.
Nov 12 14:32:47 [NTC][NET][cl105:ZeroCam] noimage: Checking for camera every 30 seconds.
Nov 12 14:32:47 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:33:17 [NTC][VID][cl105:ZeroCam] netcam_start: Norm: Opening Netcam
Nov 12 14:33:27 [NTC][NET][cl105:ZeroCam] open_context: Norm:Unable to open camera(ZeroCam):Input/output error
Nov 12 14:33:27 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:33:27 [NTC][NET][cl105:ZeroCam] noimage: Camera did not reconnect.
Nov 12 14:33:27 [NTC][NET][cl105:ZeroCam] noimage: Checking for camera every 30 seconds.
Nov 12 14:33:27 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:33:57 [NTC][VID][cl105:ZeroCam] netcam_start: Norm: Opening Netcam
Nov 12 14:34:07 [NTC][NET][cl105:ZeroCam] open_context: Norm:Unable to open camera(ZeroCam):Input/output error
Nov 12 14:34:07 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:34:07 [NTC][NET][cl105:ZeroCam] noimage: Camera did not reconnect.
Nov 12 14:34:07 [NTC][NET][cl105:ZeroCam] noimage: Checking for camera every 30 seconds.
Nov 12 14:34:07 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:34:37 [NTC][VID][cl105:ZeroCam] netcam_start: Norm: Opening Netcam
Nov 12 14:34:47 [NTC][NET][cl105:ZeroCam] open_context: Norm:Unable to open camera(ZeroCam):Input/output error
Nov 12 14:34:47 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:34:47 [NTC][NET][cl105:ZeroCam] noimage: Camera did not reconnect.
Nov 12 14:34:47 [NTC][NET][cl105:ZeroCam] noimage: Checking for camera every 30 seconds.
Nov 12 14:34:47 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:35:17 [NTC][VID][cl105:ZeroCam] netcam_start: Norm: Opening Netcam
Nov 12 14:35:27 [NTC][NET][cl105:ZeroCam] open_context: Norm:Unable to open camera(ZeroCam):Input/output error
Nov 12 14:35:27 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:35:27 [NTC][NET][cl105:ZeroCam] noimage: Camera did not reconnect.
Nov 12 14:35:27 [NTC][NET][cl105:ZeroCam] noimage: Checking for camera every 30 seconds.
Nov 12 14:35:27 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:35:57 [NTC][VID][cl105:ZeroCam] netcam_start: Norm: Opening Netcam
Nov 12 14:36:07 [NTC][NET][cl105:ZeroCam] open_context: Norm:Unable to open camera(ZeroCam):Input/output error
Nov 12 14:36:07 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:36:07 [NTC][NET][cl105:ZeroCam] noimage: Camera did not reconnect.
Nov 12 14:36:07 [NTC][NET][cl105:ZeroCam] noimage: Checking for camera every 30 seconds.
Nov 12 14:36:07 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:36:37 [NTC][VID][cl105:ZeroCam] netcam_start: Norm: Opening Netcam
Nov 12 14:36:47 [NTC][NET][cl105:ZeroCam] open_context: Norm:Unable to open camera(ZeroCam):Input/output error
Nov 12 14:36:47 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:36:47 [NTC][NET][cl105:ZeroCam] noimage: Camera did not reconnect.
Nov 12 14:36:47 [NTC][NET][cl105:ZeroCam] noimage: Checking for camera every 30 seconds.
Nov 12 14:36:47 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:37:17 [NTC][VID][cl105:ZeroCam] netcam_start: Norm: Opening Netcam
Nov 12 14:37:27 [NTC][NET][cl105:ZeroCam] open_context: Norm:Unable to open camera(ZeroCam):Input/output error
Nov 12 14:37:27 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:37:27 [NTC][NET][cl105:ZeroCam] noimage: Camera did not reconnect.
Nov 12 14:37:27 [NTC][NET][cl105:ZeroCam] noimage: Checking for camera every 30 seconds.
Nov 12 14:37:27 [NTC][NET][cl105:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:37:27 [NTC][NET][cl105:ZeroCam] Above message repeats 1 times
Nov 12 14:37:38 [NTC][ALL][cl105:ZeroCam] handler: Camera closed
Nov 12 14:37:39 [NTC][ALL][dl00:dbsl] handler: Database handler closed
Nov 12 14:37:39 [NTC][NET][cl102:ZeroCam] handler_shutdown: Norm:Shut down complete.
Nov 12 14:37:39 [NTC][NET][cl102:ZeroCam] handler_shutdown: High:Shut down complete.
Nov 12 14:37:39 [NTC][NET][cl101:PiCam] handler_shutdown: Norm:Shut down complete.
```

**Comment by Mr-Dave** [comment] 2024-11-12 17:33
Can you provide more details on the setup?  (I seem to recall that you were running some application on a different machine that creates a RTSP stream to feed into Motionplus and that other application takes a moment to start up.).  

Do all the cameras start up the first time when using ffplay?

**Comment by axeljerabek** [comment] 2024-11-12 18:49
Yes, that is right. I stream from 4 Raspberries and one Mevo camera to a central server running Ubuntu 24.04 with motionplus installed. All cams use the Nginx-RTMP module and I can fetch all 5 streams separately with vlc or any other network video player by simply typing the RTMP address. The RTMP Ngix is also on the same central server as motionplus is. The streams appear quickly and also motionplus 0.2.2 picks them up quite ok (sometimes I have to restart a stream or the nginx). But the actual master branch seems to lack this ability a bit. Occasionally, a stream is picked up, but mostly not all 5. No further info on any log level why it is not picked up, except the above log part.

**Comment by Mr-Dave** [comment] 2024-11-12 18:59
You may want to try to change the 'interrupt' parameter to something longer.  i.e. ```netcam_params interrupt=180```.  

Does ffplay start the streams without issues or warnings on the server?

I'm guessing you know this but just in case...You can also have motionplus "feed itself".  i.e. Have Motionplus on the server consume the mpegts streams of Motionplus running on the PIs.

**Comment by axeljerabek** [comment] 2024-11-12 19:17
Ok, I could try that. I do not use ffplay, but I can start all streams without issues with ffplay. The streams seem to be fine, since they also do any transcoding with any software quite fine.
Yes, that was an option, but the Pi's are rather weak (zero 2w) and any increase in bandwith (mjpeg vs h264) or encoding load is too much. I use the camera itself to create the h264 and wrap it into flv, which does not consume any processing power at all.

**Comment by Mr-Dave** [comment] 2024-11-13 00:46
I'm not immediately seeing anything as to the cause and all my cameras are starting ok.   

Maybe increase to ```log_level 7``` as well as ```log_fflevel 8``` will show something.

**Comment by axeljerabek** [comment] 2024-11-13 03:22
Increased the loglevels and tried a few times. There are three different logfiles here:
https://home.jerabek.fi/s/NsikHgZqPdi2PjM

Two are with the actual master branch, but only one of three cams was working in those cases. The other logfiles is from the 0.2.2 release with at least two cams working, but almost immediately. Just to mention this: sometimes, also the master branch works with all cams and runs smooth and stable for a few days even.

The `netcam_params interrupt=180` did not bring any cure it seems.

**Comment by Mr-Dave** [comment] 2024-11-15 18:39
I did review the logs but didn't see Motionplus failing to connect on the current master.  It looked like it only failed on the 0.2 version but I may have missed it.  In the logs tagged "working" did you observe that it wasn't connecting?  

(It could be that all those errors with the PTS/DTS are causing the connection problem but I'm not sure.)

**Comment by axeljerabek** [comment] 2024-11-16 05:13
The two logs with the "working" suffix are logs where one cam is working and the others are not. The v0.2.2 one is working fine, except with one cam that was switched off.
I also cannot see anything in the logs :/

**Comment by axeljerabek** [comment] 2024-11-18 05:53
I create the streams with rpicam-vid, send it to an nginx with rtmp module and from there it is fetched with motionplus:

nice -12 rpicam-vid -t 0 --width 1920 --height 1080 --hdr off --nopreview --exposure normal --sharpness 1.1 --contrast 1.1 --brightness 0.1 --saturation 1.0 --awb auto \
--denoise auto --profile main --level 4.2 --codec libav --libav-audio --audio-source alsa --audio-device hw:0,0 --audio-channels 1 --audio-codec aac \
--audio-samplerate 48000 --audio-bitrate 128000 --av-sync 0 --libav-format flv -n --framerate 30 -b 6000000 --autofocus-mode manual --lens-position 0.5 \
--autofocus-window 0.25,0.25,0.5,0.5 --inline  -o "rtmp://192.168.178.25/zero/test"

The is over wifi or ethernet. All streams can be accessed with vlc or ffplay at any time. ffprobe also does not give anything weird:

root@home:/home/axel/dev/motionplus/motionplus-master# ffprobe -i rtmp://192.168.178.25/pi/test -show_streams -show_format -pretty -loglevel verbose
ffprobe version 7.1-0ubuntu0.22.04.1+esm1 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1+esm1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-libsvtav1 --enable-libfdk-aac --enable-vaapi --enable-vdpau --enable-libx264 --enable-cuda --enable-libvmaf --enable-libtesseract --enable-vulkan --enable-librav1e --enable-libopenh264 --enable-frei0r --enable-version3 --enable-nonfree --enable-shared --enable-libvpl --enable-libsvtav1
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
[tcp @ 0x603f5434ff80] Starting connection attempt to 192.168.178.25 port 1935
[tcp @ 0x603f5434ff80] Successfully connected to 192.168.178.25 port 1935
[h264 @ 0x603f54380540] Reinit context to 1920x1088, pix_fmt: yuv420p
Input #0, flv, from 'rtmp://192.168.178.25/pi/test':
  Metadata:
    |RtmpSampleAccess: true
    encoder         : Lavf59.27.100
  Duration: 00:00:00.00, start: 82907.222000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), 1 reference frame, yuv420p(progressive, left), 1920x1080, 6000 kb/s, 30 fps, 30 tbr, 1k tbn
  Stream #0:1: Audio: aac (LC), 48000 Hz, mono, fltp, 128 kb/s
[STREAM]
index=0
codec_name=h264
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
profile=Main
codec_type=video
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
width=1920
height=1080
coded_width=1920
coded_height=1080
closed_captions=0
film_grain=0
has_b_frames=0
sample_aspect_ratio=N/A
display_aspect_ratio=N/A
pix_fmt=yuv420p
level=40
color_range=unknown
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=left
field_order=progressive
refs=1
is_avc=true
nal_length_size=4
missing_streams=0
id=N/A
r_frame_rate=30/1
avg_frame_rate=30/1
time_base=1/1000
start_pts=83789373
start_time=23:16:29.373000
duration_ts=N/A
duration=N/A
bit_rate=6 Mbit/s
max_bit_rate=N/A
bits_per_raw_sample=8
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
extradata_size=52
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
DISPOSITION:non_diegetic=0
DISPOSITION:captions=0
DISPOSITION:descriptions=0
DISPOSITION:metadata=0
DISPOSITION:dependent=0
DISPOSITION:still_image=0
DISPOSITION:multilayer=0
[/STREAM]
[STREAM]
index=1
codec_name=aac
codec_long_name=AAC (Advanced Audio Coding)
profile=LC
codec_type=audio
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
sample_fmt=fltp
sample_rate=48 KHz
channels=1
channel_layout=mono
bits_per_sample=0
initial_padding=0
missing_streams=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/1000
start_pts=82907222
start_time=23:01:47.222000
duration_ts=N/A
duration=N/A
bit_rate=128 Kbit/s
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
extradata_size=5
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
DISPOSITION:non_diegetic=0
DISPOSITION:captions=0
DISPOSITION:descriptions=0
DISPOSITION:metadata=0
DISPOSITION:dependent=0
DISPOSITION:still_image=0
DISPOSITION:multilayer=0
[/STREAM]
[FORMAT]
filename=rtmp://192.168.178.25/pi/test
nb_streams=2
nb_programs=0
nb_stream_groups=0
format_name=flv
format_long_name=FLV (Flash Video)
start_time=23:01:47.222000
duration=0:00:00.000000
size=N/A
bit_rate=N/A
probe_score=100
TAG:|RtmpSampleAccess=true
TAG:encoder=Lavf59.27.100
[/FORMAT]
[AVIOContext @ 0x603f54380080] Statistics: 908288 bytes read, 0 seeks

Nothing weird on any of those 5 streams. Movie passthrough and the h264 streams are created directly on the camera sensors, then packed into flv with ffmpeg (variants 7.1, 7.02. 6.1 etc). Cam module v2 and v3 from Raspberry, and one Mevo Camera that also sends the stream via RTMP to nginx. No further encoding or transcoding in between. As I said, all streams are instantly visible on any player, only motionplus needs a while to pick them up. And sometimes it does not at all.

**Comment by Mr-Dave** [comment] 2024-11-19 00:09
Ok.  I understand.  This just isn't something that I've observed or can reproduce.

**Comment by Mr-Dave** [comment] 2024-11-29 03:05
Motionplus tested without issue using arut/nginx-rtmp-module and this issue not observed issue with other cameras.  If patch created, post to this issue and it will be considered for inclusion.

Closing as not planned.

**Closed** 2024-11-29 03:12 UTC
Labels: bug, Unable to Reproduce
